---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-storage-config
type: generic
stringData:
  thanos.yaml: |-
    type: s3
    config:
      bucket: thanos-store-${app}-${env}-${aws_region}
      endpoint: thanos-store-${app}-${env}-${aws_region}
      access_key: ${access_key}
      secret_key: ${secret_key}
